# This file is generated by the BAML compiler.
# Do not edit this file directly.
# Instead, edit the BAML files and recompile.

# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off



from .fx_classifyconversation_impl_default_config import default_config as unused_fx_classifyconversation_impl_default_config
from .fx_extractresume_impl_default_config import default_config as unused_fx_extractresume_impl_default_config
