# This file is generated by the BAML compiler.
# Do not edit this file directly.
# Instead, edit the BAML files and recompile.

# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off

from ..clients.client_gpt4 import GPT4
from ..functions.fx_extractresume import BAMLExtractResume
from ..types.classes.cls_education import Education
from ..types.classes.cls_resume import Resume
from ..types.partial.classes.cls_education import PartialEducation
from ..types.partial.classes.cls_resume import PartialResume
from baml_core.jinja.render_prompt import RenderData
from baml_core.provider_manager.llm_response import LLMResponse
from baml_core.stream import AsyncStream
from baml_lib._impl.deserializer import Deserializer


import typing
# Impl: default_config
# Client: GPT4
# An implementation of ExtractResume.

__prompt_template = """\
Parse the following resume and return a structured representation of the data in the schema below.

Resume:
---
{{text}}
---

{# output_format is a helper to print out Resume #}
{{ ctx.output_format }}

Output JSON:\
"""

# We ignore the type here because baml does some type magic to make this work
# for inline SpecialForms like Optional, Union, List.
__deserializer = Deserializer[Resume](Resume)  # type: ignore

# Add a deserializer that handles stream responses, which are all Partial types
__partial_deserializer = Deserializer[PartialResume](PartialResume)  # type: ignore

__output_format = """
{
  "name": string,
  "education": {
    "school": string,
    "degree": string,
    "year": int
  }[],
  "skills": string[]
}
""".strip()

__template_macros = [
]


async def default_config(*, text: str) -> Resume:
    response = await GPT4.run_jinja_template(
        jinja_template=__prompt_template,
        output_format=__output_format, template_macros=__template_macros,
        args=dict(text=text)
    )
    deserialized = __deserializer.from_string(response.generated)
    return deserialized


def default_config_stream(*, text: str
) -> AsyncStream[Resume, PartialResume]:
    def run_prompt() -> typing.AsyncIterator[LLMResponse]:
        raw_stream = GPT4.run_jinja_template_stream(
            jinja_template=__prompt_template,
            output_format=__output_format, template_macros=__template_macros,
            args=dict(text=text)
        )
        return raw_stream
    stream = AsyncStream(stream_cb=run_prompt, partial_deserializer=__partial_deserializer, final_deserializer=__deserializer)
    return stream

BAMLExtractResume.register_impl("default_config")(default_config, default_config_stream)